### PR TITLE
Update sssom-schema

### PR DESCRIPTION
**Pull request by hrshdhgd**
ran `poetry add sssom-schema@latest`

### CODE REVIEW

**Review by matentzn — DISMISSED** [review]

**Comment by matentzn** [comment]
Some stuff broke?

**Comment by hrshdhgd** [comment]
Yes the test is failing because the [rdf test file](https://github.com/mapping-commons/sssom-py/blob/master/tests/data/basic.sssom.rdf) does not have subject_id. Did we use some other file to convert to rdf. I can recreate it?

**Comment by matentzn** [comment]
The RDF file does have a subject_id, but it is _mapped_ to some other relation. Check Slack for details.

**Comment by hrshdhgd** [comment]
This also passes now

**Review by matentzn — APPROVED** [review]
Thanks!!

**Pull request merged**
