### PR TITLE
Add windows testing and update path construction

### PR DESCRIPTION
**Pull request by cthoyt**
A lot of file paths inside the tests were being constructed with string concatenation. This PR introduces `pathlib` (i.e., the high level interface) in many places and switches over to `os` (i.e., the low-level interface) for the rest. This also makes it possible to pass tests on Windows, so I added that to the GitHub actions as well.

### CODE REVIEW

**Comment by matentzn** [comment]
@cthoyt was this ready? we are getting ready to merge the remaining PRs next week to make a new release..

**Review by hrshdhgd — DISMISSED** [review]
Looks good to me.

**Review by hrshdhgd — APPROVED** [review]
Resolved conflicts and ran flake8 + linter to pass GH Actions.

**Review by matentzn — APPROVED** [review]
I have never seen this kind of syntax (using a `/` straight in the path rather than os.path.join()), but I will trust your judgement @cthoyt.

Thank you for this!

**Pull request merged**
