### PR TITLE
Remove deprecated MetaTSVConverter

### PR DESCRIPTION
**Pull request by cthoyt**
This code is unused and is marked as deprecated. Rather than trying to fix it in #143, it might just be better to delete it now.

### CODE REVIEW

**Comment by cthoyt** [comment]
@matentzn I think the failing tests are due to something unrelated to this PR with RDFlib's JSON-LD plugin

**Comment by matentzn** [comment]
I assigned @cmungall  to this to take a look, but I have no objections myself. If we don't hear from him in 2 days, we can merge.

**Review by matentzn — APPROVED** [review]

**Comment by matentzn** [comment]
Is it possible we need: https://github.com/mapping-commons/sssom-py/pull/148

**Comment by cthoyt** [comment]
@matentzn please mark as approved so we can merge

**Review by matentzn — APPROVED** [review]

**Pull request merged**
