### PR TITLE
What to do when having a uri-prefix clash?

### PR DESCRIPTION
**Pull request by matentzn**
Note: If you remove either one of the two prefixes, it works

### CODE REVIEW

**Comment by cthoyt** [comment]
Okay this is a good demo. Do you think it will be possible to come up with a consistent set of rules for this kind of merge where in your higher priority EPM, you have two disparate records that a lower priority EPM in the chain would merge together?

**Comment by matentzn** [comment]
@hrshdhgd lets make sure that the test fails (assertRaises) and maybe wrap the exception in something more progressive that helps users actually dealing with the clash.

Also we should make sure that the raised exception mentions the clash. I don't know how hard/easy that is, but for now I would just make an issue in the curies repo asking for a messages that "involves all prefixes that are part of the clash", not just the last one.

**Comment by cthoyt** [comment]
sorry all I have not had time to write an excellent tutorial on this yet. I would like you to let `curies` do the hard work of documenting this to make sure that it's absolutely excellent. Contributions welcome if you want to get started solving this issue upstream in a PR there.

**Comment by hrshdhgd** [comment]
@matentzn : Test should pass now.

**Review by matentzn — COMMENTED** [review]
Approved!

Thanks!

**Pull request merged**
