### PR TITLE
updated sphinx docs per changes in docstrings

### PR DESCRIPTION
**Pull request by hrshdhgd**

### CODE REVIEW

**Comment by cthoyt** [comment]
This PR should be blocked by #164 since it adds even more docstrings

**Comment by matentzn** [comment]
Not ready for review yet so no worries

**Comment by hrshdhgd** [comment]
This PR is addressed by #164 and this in turn addresses issue #179

**Comment by hrshdhgd** [comment]
It still gives errors on building docs as mentioned in #159

**Comment by matentzn** [comment]
I leave this in your good care, please deal as you see fit.

**Pull request merged**
