### PR TITLE
Migrating to Linkml 1.0.0

### PR DESCRIPTION
**Pull request by matentzn**
somehow continuous integration stopped working with the recent release of linkml 0.0.7

I can seem to be able to migrate though - see slack.

### CODE REVIEW

**Comment by matentzn** [comment]
@wdduncan I assigned you here to just check the situation - in case you have more experience then us!

**Comment by hrshdhgd** [comment]
I believe the migration is complete!

**Comment by wdduncan** [comment]
@matentzn sorry ... you and @hrshdhgd  have as much experience in this as I do

**Comment by matentzn** [comment]
No problem Bill. :) we are all learning!

**Comment by joeflack4** [comment]
Yes, would be very nice to merge this. See: https://github.com/mapping-commons/sssom-py/issues/95

**Comment by matentzn** [comment]
There are still problems with the pull request but @hrshdhgd maybe contrary do what we discussed @cmungall wants this for the milestone..

**Comment by hrshdhgd** [comment]
I ran `make install all_schemas` on this branch and none of the files changed and the tests run successfully. One of two conclusions:

- The autogeneration does what it's supposed to and matches the changes I made
- The autogeneration does not work at all.

I'll keep digging.

**Comment by matentzn** [comment]
Some of them at least used to change with an updated date. Maybe digg through Makefile?

**Comment by hrshdhgd** [comment]
It didn't do anything previously because I used `make install all_schemaS` ...the extra 's' basically caused it to do nothing.

**Comment by matentzn** [comment]
Thank you @hrshdhgd great work. Merging this now, but @joeflack4 I would still resist the temptation of migrating the this version.. Lots of function changes imminent..

**Pull request merged**
