### PR TITLE
Migrated files from charlies PR

### PR DESCRIPTION
**Pull request by matentzn**
This is the exact same pull request as #90 

it was erroneously created because of my inability to work with a forked repo i didn't have write rights to - and which had conflicts with master. Now I know better :)

### CODE REVIEW

**Comment by matentzn** [comment]
Merged all of @cthoyt s commits in. @hrshdhgd yours!

**Comment by cthoyt** [comment]
Still not exactly sure what's different here from my PR... could you update the description please?

**Comment by matentzn** [comment]
There is absolutely no difference.. Sorry this was a bit of a communication error; we were in a meeting and wanted to quickly work on the branch - no changes to your work (apart from 2 or 3  dependencies in setup.cfg). If you want us to redo this from scratch to be more transparent then we can!

**Comment by matentzn** [comment]
Closing this now, superseded by #114

**Pull request closed without merging**
